### ISSUE TITLE
Error "The directory of the storage does not exist"

### ISSUE THREAD

**Issue by dreamon11** [terrylinooo/cache-master#3]
Hi,

When activating plugin, I have this error:

```
wp plugin activate cache-master

PHP Fatal error:  Uncaught Shieldon\SimpleCache\Exception\CacheException: The directory of the storage does not exist. in /srv/www/site.com/current/web/app/plugins/cache-master/vendor/shieldon/simple-cache/src/SimpleCache/AssertTrait.php:110
Stack trace:
#0 /srv/www/site.com/current/web/app/plugins/cache-master/vendor/shieldon/simple-cache/src/SimpleCache/Driver/File.php(54): Shieldon\SimpleCache\CacheProvider->assertDirectoryWritable()
#1 /srv/www/site.com/current/web/app/plugins/cache-master/vendor/shieldon/simple-cache/src/SimpleCache/Cache.php(53): Shieldon\SimpleCache\Driver\File->__construct()
#2 /srv/www/site.com/current/web/app/plugins/cache-master/inc/helpers.php(203): Shieldon\SimpleCache\Cache->__construct()
#3 /srv/www/site.com/current/web/app/plugins/cache-master/inc/class-cache-master.php(58): scm_driver_factory()
#4 /srv/www/site.com/current/web/app/plugins/cache-master/cache-master.php(99): Cache_Master->__construct()
#5 /srv/www/site.com/current/web/wp/wp-settin in /srv/www/site.com/current/web/app/plugins/cache-master/vendor/shieldon/simple-cache/src/SimpleCache/AssertTrait.php on line 110
Fatal error: Uncaught Shieldon\SimpleCache\Exception\CacheException: The directory of the storage does not exist. in /srv/www/site.com/current/web/app/plugins/cache-master/vendor/shieldon/simple-cache/src/SimpleCache/AssertTrait.php:110
Stack trace:
#0 /srv/www/site.com/current/web/app/plugins/cache-master/vendor/shieldon/simple-cache/src/SimpleCache/Driver/File.php(54): Shieldon\SimpleCache\CacheProvider->assertDirectoryWritable()
#1 /srv/www/site.com/current/web/app/plugins/cache-master/vendor/shieldon/simple-cache/src/SimpleCache/Cache.php(53): Shieldon\SimpleCache\Driver\File->__construct()
#2 /srv/www/site.com/current/web/app/plugins/cache-master/inc/helpers.php(203): Shieldon\SimpleCache\Cache->__construct()l
#3 /srv/www/site.com/current/web/app/plugins/cache-master/inc/class-cache-master.php(58): scm_driver_factory()
#4 /srv/www/site.com/current/web/app/plugins/cache-master/cache-master.php(99): Cache_Master->__construct()
#5 /srv/www/site.com/current/web/wp/wp-settin in /srv/www/site.com/current/web/app/plugins/cache-master/vendor/shieldon/simple-cache/src/SimpleCache/AssertTrait.php on line 110

Error: une erreur critique est survenue sur votre site.En apprendre plus sur le débogage de WordPress. une erreur critique est survenue sur votre site.
```

Can you help?

Thanks.

**Comment by terrylinooo** [comment]
Thanks for reporting issues.
Fixed it in 2.0.2, could you download and try it again?

**Comment by dreamon11** [comment]
Thanks for help, but still the same error with 2.0.2:

```
$ wp plugin list

+--------------------------+----------+-----------+---------+
| name                     | status   | update    | version |
+--------------------------+----------+-----------+---------+
| cache-master             | inactive | none      | 2.0.2   |
```

```
$ wp plugin activate cache-master

PHP Fatal error:  Uncaught Shieldon\SimpleCache\Exception\CacheException: The directory of the storage does not exist. in /srv/www/site.com/current/web/app/plugins/cache-master/vendor/shieldon/simple-cache/src/SimpleCache/AssertTrait.php:110
Stack trace:
#0 /srv/www/site.com/current/web/app/plugins/cache-master/vendor/shieldon/simple-cache/src/SimpleCache/Driver/File.php(54): Shieldon\SimpleCache\CacheProvider->assertDirectoryWritable()
#1 /srv/www/site.com/current/web/app/plugins/cache-master/vendor/shieldon/simple-cache/src/SimpleCache/Cache.php(53): Shieldon\SimpleCache\Driver\File->__construct()
#2 /srv/www/site.com/current/web/app/plugins/cache-master/inc/helpers.php(211): Shieldon\SimpleCache\Cache->__construct()
#3 /srv/www/site.com/current/web/app/plugins/cache-master/inc/class-cache-master.php(58): scm_driver_factory()
#4 /srv/www/site.com/current/web/app/plugins/cache-master/cache-master.php(102): Cache_Master->__construct()
#5 /srv/www/site.com/current/web/wp/wp-admin in /srv/www/site.com/current/web/app/plugins/cache-master/vendor/shieldon/simple-cache/src/SimpleCache/AssertTrait.php on line 110
Fatal error: Uncaught Shieldon\SimpleCache\Exception\CacheException: The directory of the storage does not exist. in /srv/www/site.com/current/web/app/plugins/cache-master/vendor/shieldon/simple-cache/src/SimpleCache/AssertTrait.php:110
Stack trace:
#0 /srv/www/site.com/current/web/app/plugins/cache-master/vendor/shieldon/simple-cache/src/SimpleCache/Driver/File.php(54): Shieldon\SimpleCache\CacheProvider->assertDirectoryWritable()
#1 /srv/www/site.com/current/web/app/plugins/cache-master/vendor/shieldon/simple-cache/src/SimpleCache/Cache.php(53): Shieldon\SimpleCache\Driver\File->__construct()
#2 /srv/www/site.com/current/web/app/plugins/cache-master/inc/helpers.php(211): Shieldon\SimpleCache\Cache->__construct()
#3 /srv/www/site.com/current/web/app/plugins/cache-master/inc/class-cache-master.php(58): scm_driver_factory()
#4 /srv/www/site.com/current/web/app/plugins/cache-master/cache-master.php(102): Cache_Master->__construct()
#5 /srv/www/site.com/current/web/wp/wp-admin in /srv/www/site.com/current/web/app/plugins/cache-master/vendor/shieldon/simple-cache/src/SimpleCache/AssertTrait.php on line 110
```

**Comment by terrylinooo** [comment]
Can you try it on the website, not from CLI.

**Comment by dreamon11** [comment]
I manage to activate the plugin via the website but the website is then inaccessible : "A critical error has occurred on your website"

**Comment by terrylinooo** [comment]
@dreamon11 Thanks so much to help me debug this issue. I've just updated this plugin to 2.0.3, please try again.

**Comment by dreamon11** [comment]
Thanks, it works now! 👍 
CLI and website = OK

**Comment by terrylinooo** [comment]
@dreamon11 Glad to hear this good news. Thanks again for reporting issues. Have a good day.
